### PR TITLE
Fix radio inputs not being isolated between radio input items

### LINKED ISSUE #171: Radio components inside editgrids are not isolated from each other
Discovered/reported by Laurens in in https://github.com/open-formulieren/open-forms-sdk/issues/863

When you have a repeating group with a radio component, interacting with it in one item affects other items (when they are both in edit mode!).

Root cause: the `name` attribute is picked up and native browser radio group handling kicks in.

### PR DESCRIPTION
**Pull request by sergei-maertens**
Closes #171

Major rework needed to fight against the browser :(

**TODO**

- [x] Fix type information, there are some lies now

### CODE REVIEW

File: src/components/forms/EditGrid/EditGrid.tsx [hunk 1]
```diff
@@ -202,4 +214,124 @@ function EditGrid<T extends {[K in keyof T]: JSONValue} = JSONObject>({
...
+      const itemValues: T = getIn(values, namePrefix);
+
+      try {
+        await validateCallback(index, itemValues);
+      } catch (err: unknown) {
+        // only handle errors we know
+        if (!isValidationError(err)) throw err;
+        err.inner.forEach(problem => {
+          problem.path = `${namePrefix}.${problem.path}`;
+        });
```
Comment (robinmolen) [inline src/components/forms/EditGrid/EditGrid.tsx]: Does this not need to be a Array.map?

**Review by robinmolen — APPROVED** [review]
Edit grid really is a proper pain..

I think this is correct, I haven't managed to break it 😄.

Maybe its a good idea to add storybook tests that the errors are still shown correctly in this situation (i've made a quick setup, and it seems fine, but still good to cover)

**Comment by sergei-maertens** [comment]
> Edit grid really is a proper pain..
> 
> I think this is correct, I haven't managed to break it 😄.
> 
> Maybe its a good idea to add storybook tests that the errors are still shown correctly in this situation (i've made a quick setup, and it seems fine, but still good to cover)

I was going to do this, but checked and there already is a story with a validation error from the schema build through the formio component validation options in `?path=/story/component-registry-special-editgrid--with-validation-schema`

There are also stories for the low-level edit grid component that pass errors, and the important part in this rework was that the external API would not change (still pass in the same structure of data/errors etc.). I don't see which additional stories we can make in storybook tbh.
