### PR TITLE
FIx the anchor target attribute being stripped

### LINKED ISSUE #6190: "target" missing in links in content component (not opening new tab)
### Product versie / Product version

3.4.x

### Customer reference

Leiden 51

### Omschrijf het probleem / Describe the bug

while the link does get a `rel="noopener noreferrer"` when selecting `open in a new tab`:

Image

The `target="_blank"` is missing:

Image

### Stappen om te reproduceren / Steps to reproduce

_No response_

### Verwacht gedrag / Expected behavior

_No response_

### Screen resolution

None

### Device

None

### OS

None

### Browser

_No response_

**Tasks**

- [x] Fix in renderer (& backport)
- [x] Update SDK
    - [x] main
    - [x] stable/3.5.x
    - [x] stable/3.4.x

### PR DESCRIPTION
**Pull request by sergei-maertens**
Partly closes open-formulieren/open-forms#6190

### CODE REVIEW

File: src/registry/content/index.tsx [hunk 1]
```diff
@@ -2,11 +2,19 @@ import type {ContentComponentSchema} from '@open-formulieren/types';
 import {HTMLContent} from '@utrecht/component-library-react';
 import {clsx} from 'clsx';
 import DOMPurify from 'dompurify';
+import type {Config} from 'dompurify';
 
 import type {RegistryEntry} from '@/registry/types';
 
 import './Content.scss';
 
+const DOM_PURIFY_CFG: Config = {
```
Comment (SonnyBA) [inline src/registry/content/index.tsx:11]: We could move this configuration to a more generic file (`utils.js`?) if other components need sanitization too.

**Review by SonnyBA — APPROVED** [review]

File: src/registry/content/index.tsx (hunk 1 above)
Comment (sergei-maertens) [reply src/registry/content/index.tsx:11]: I think I'd rather have a dedicated `WYSIWYGContent` component instead that encapsulates this - we currently still have a mess in the backend with multiple editors anyway.

**Comment by sergei-maertens** [comment]
Backported to stable/1.1.x in cf2151d9071470dff200e15e5f8c1b2f4983d3a0
